/**
 * GET /api/employee/:id — the itinerary read the roster deliberately does not do.
 *
 * PLAN-dashboard.md:576 drops segments[] from the roster payload on purpose:
 * the card renders a sentence, not flight rows, and carrying them fans 26 rows
 * into 34. This is the endpoint that was always meant to fetch them, specified
 * at PLAN-dashboard.md:124 and never built until now.
 *
 * RUNTIME-AGNOSTIC ON PURPOSE
 * ---------------------------
 * Everything here goes through a `Querier` rather than touching D1 directly, so
 * the exact same SQL runs in three places: the worker against D1, the fixture
 * generator against bun:sqlite, and any future test harness. The frontend
 * fixture is generated by executing this file against the real schema and seed,
 * which is what makes fixture drift structurally impossible rather than merely
 * discouraged.
 *
 * NEVER JOINS booking_snapshot. `raw_json` is the full get-booking payload and
 * reshop responses run ~170KB (PLAN-dashboard.md:578). It sits one FK away and
 * looks innocent.
 */

export type Row = Record<string, unknown>
export type Querier = (sql: string, params: unknown[]) => Promise<Row[]>

export interface FlightSegment {
  id: string
  type: "FLIGHT"
  carrier: string
  flightNo: number
  operatingCarrier: string | null
  operatingFlightNo: number | null
  origin: string
  dest: string
  depAt: string
  arrAt: string
  status: string | null
}

export interface HotelSegment {
  id: string
  type: "HOTEL"
  propertyName: string | null
  propertyPhone: string | null
  checkIn: string
  checkOut: string
  freeCancelUntil: string | null
  status: string | null
}

export type ItinerarySegment = FlightSegment | HotelSegment

export interface ItineraryRecord {
  id: string
  component: "FLIGHT" | "HOTEL"
  pnr: string
  ticketNumber: string | null
  status: string | null
  segments: ItinerarySegment[]
}

export interface ActivityItem {
  id: string
  kind: string
  venue: string
  address: string | null
  phone: string | null
  startsAt: string
  timezone: string
}

export interface OfferOption {
  id: string
  rank: number
  routeSummary: string | null
  arrivesAt: string | null
  chargeType: "ADD_COLLECT" | "EVEN" | "REFUND" | null
  currency: string | null
  totalDelta: string | null
  policyVerdict: "PASS" | "NEEDS_APPROVAL" | "FAIL" | null
  policyReason: string | null
  expiresAt: string | null
}

export interface EmployeeItinerary {
  itineraries: ItineraryRecord[]
  activities: ActivityItem[]
  offers: OfferOption[]
}

/** Flights first — it is the component that breaks and the one people scan for. */
const ITINERARY_SQL = `
  SELECT id, component, pnr, ticket_number, status
  FROM itinerary
  WHERE employee_id = ? AND event_id = ?
  ORDER BY CASE component WHEN 'FLIGHT' THEN 0 ELSE 1 END, id
`

const SEGMENT_SQL = `
  SELECT s.id, s.itinerary_id, s.type,
         s.carrier, s.flight_no, s.operating_carrier, s.operating_flight_no,
         s.origin, s.dest, s.dep_time_utc, s.arr_time_utc,
         s.property_name, s.property_phone,
         s.check_in, s.check_out, s.free_cancel_until,
         s.status
  FROM segment s
  JOIN itinerary i ON i.id = s.itinerary_id
  WHERE i.employee_id = ? AND i.event_id = ?
  ORDER BY COALESCE(s.dep_time_utc, s.check_in)
`

/**
 * Through `attendance`, not every activity on the event. Someone who declined
 * the dinner should not see it on their own itinerary.
 */
const ACTIVITY_SQL = `
  SELECT a.id, a.kind, a.venue, a.address, a.phone, a.starts_at, a.timezone
  FROM activity a
  JOIN attendance att ON att.activity_id = a.id
  WHERE a.event_id = ? AND att.employee_id = ? AND att.attend_state <> 'DECLINED'
  ORDER BY a.starts_at
`

/**
 * ORDER BY rank, never WHERE rank = 1. Rank is a priority, not a dense sequence
 * (schema.sql:209) — ranks 1/3/5 are read out as "1, 2, 3".
 */
const OFFER_SQL = `
  SELECT o.id, o.rank, o.route_summary, o.arrives_at, o.charge_type, o.currency,
         o.total_delta, o.policy_verdict, o.policy_reason, o.expires_at
  FROM offer o
  JOIN disruption_impact imp ON imp.id = o.impact_id
  WHERE imp.employee_id = ? AND imp.state <> 'RESOLVED'
  ORDER BY o.rank
`

const str = (v: unknown): string | null => (v === null || v === undefined ? null : String(v))
const num = (v: unknown): number | null => (v === null || v === undefined ? null : Number(v))

function toSegment(r: Row): ItinerarySegment {
  if (r.type === "FLIGHT") {
    return {
      id: String(r.id),
      type: "FLIGHT",
      carrier: String(r.carrier ?? ""),
      flightNo: Number(r.flight_no ?? 0),
      operatingCarrier: str(r.operating_carrier),
      operatingFlightNo: num(r.operating_flight_no),
      origin: String(r.origin ?? ""),
      dest: String(r.dest ?? ""),
      depAt: String(r.dep_time_utc ?? ""),
      arrAt: String(r.arr_time_utc ?? ""),
      status: str(r.status),
    }
  }
  return {
    id: String(r.id),
    type: "HOTEL",
    propertyName: str(r.property_name),
    propertyPhone: str(r.property_phone),
    checkIn: String(r.check_in ?? ""),
    checkOut: String(r.check_out ?? ""),
    freeCancelUntil: str(r.free_cancel_until),
    status: str(r.status),
  }
}

export async function loadEmployeeItinerary(
  query: Querier,
  employeeId: string,
  eventId: string
): Promise<EmployeeItinerary> {
  const [itinRows, segRows, actRows, offerRows] = await Promise.all([
    query(ITINERARY_SQL, [employeeId, eventId]),
    query(SEGMENT_SQL, [employeeId, eventId]),
    query(ACTIVITY_SQL, [eventId, employeeId]),
    query(OFFER_SQL, [employeeId]),
  ])

  const byItinerary = new Map<string, ItinerarySegment[]>()
  for (const r of segRows) {
    const key = String(r.itinerary_id)
    const list = byItinerary.get(key) ?? []
    list.push(toSegment(r))
    byItinerary.set(key, list)
  }

  return {
    itineraries: itinRows.map((r) => ({
      id: String(r.id),
      component: r.component === "FLIGHT" ? "FLIGHT" : "HOTEL",
      pnr: String(r.pnr ?? ""),
      ticketNumber: str(r.ticket_number),
      status: str(r.status),
      segments: byItinerary.get(String(r.id)) ?? [],
    })),
    activities: actRows.map((r) => ({
      id: String(r.id),
      kind: String(r.kind ?? ""),
      venue: String(r.venue ?? ""),
      address: str(r.address),
      phone: str(r.phone),
      startsAt: String(r.starts_at ?? ""),
      // The row's own zone. A dinner happens where it happens, and the renderer
      // shows it in both that zone and the viewer's.
      timezone: String(r.timezone ?? "UTC"),
    })),
    offers: offerRows.map((r) => ({
      id: String(r.id),
      rank: Number(r.rank ?? 0),
      routeSummary: str(r.route_summary),
      arrivesAt: str(r.arrives_at),
      chargeType: (str(r.charge_type) ?? null) as OfferOption["chargeType"],
      currency: str(r.currency),
      totalDelta: str(r.total_delta),
      policyVerdict: (str(r.policy_verdict) ?? null) as OfferOption["policyVerdict"],
      policyReason: str(r.policy_reason),
      expiresAt: str(r.expires_at),
    })),
  }
}
